#! /usr/bin/env bash

(
    { echo '* lscpu'
      lscpu | sed 's/^/  /'
    }
    { echo '* memory'
      echo $(( 1024 * $(grep MemTotal /proc/meminfo  | gawk '{ print $2; }') )) | tounits | sed 's/^/  /'
    }
    { echo '* disks'
      lsblk | sed 's/^/  /'
    }
    { echo '* display'
      xdpyinfo | sed -n -e '/screen #/,+3p' | sed  's/^/  /'
    }
) | tee ~/Repos/tkb-notes/Computer/Capabilities/$(hostname)-capabilities.org
