#! /usr/bin/env bash
URL=$1
DEST=$2

if [[ ${URL} == "https://github.com/alire-project/GNAT-FSF-builds/releases/download/gnatprove-16.1.0-1/gnatprove-x86_64-linux-16.1.0-1.tar.gz" ]]; then
    cp /home/tkb/tmp/alire/gnatprove-x86_64-linux-16.1.0-1.tar.gz ${DEST}
else
    curl ${URL} -sSfL -o ${DEST}
fi
