#! /usr/bin/env bash

# Needed the before-sleep to prevent harmless error message.

swayidle \
    timeout 300 'swaymsg "output * power off"' resume 'swaymsg "output * power on"' \
    before-sleep 'true' &
