#! /usr/bin/env bash
# This only works if run from the correct place!
# 
# The NCURSES HOWTO SGML files look for the C source of the example
# programs to include in the output in a specific relative place.

(cd /usr/local/sw/src/lang/C/TLDP/LDP/LDP/howto/docbook/NCURSES-Programming-HOWTO/
 STYLESHEET=/usr/share/sgml/docbook/dsssl-stylesheets-1.79/html/docbook.dsl
 # This doesn't work:
 #STYLESHEET=mystyle.dsl
 echo Building in $(pwd)
 echo Building one big output file
 openjade -t sgml -i html \
          -d $STYLESHEET \
          -V nochunks \
          /usr/local/sw/src/lang/C/TLDP/LDP/LDP/howto/docbook/NCURSES-Programming-HOWTO/NCURSES-Programming-HOWTO.sgml > ~/Reference/Computer/Languages/C/NCURSES-HOWTO/NCURSES-ONE-BIG-FILE.html
 echo 'Building multiple output files IN THE CURRENT DIRECTORY!'
 openjade -t sgml -i html \
          -d $STYLESHEET \
          -V use-output-dir \
          /usr/local/sw/src/lang/C/TLDP/LDP/LDP/howto/docbook/NCURSES-Programming-HOWTO/NCURSES-Programming-HOWTO.sgml
 cp -v *.htm ~/Reference/Computer/Languages/C/NCURSES-HOWTO/multinode/
)

# This doesn't work.
# openjade -t tex -i html \
#          -d /usr/share/sgml/docbook/dsssl-stylesheets-1.79/print/docbook.dsl \
#         -V nochunks \
#    /usr/local/sw/src/lang/C/LDP/LDP/howto/docbook/NCURSES-Programming-HOWTO/NCURSES-Programming-HOWTO.sgml > ~/tmp/NCURSES-ONE-BIG-FILE.tex
