#! /usr/bin/env bash

echo "current files: $*"

for file in $@
do
    for egg in $(cat $file | sed 's/[ \t]*#.*$//')
    do
        if [[ -z $(chicken-status $egg) ]]; then
            printf "Missing %s\n" $egg
        fi
    done
done
