#! /usr/bin/env bash

function NYI {
    echo $0: not yet implemented: "$@"
    exit 2
}

THREADS=1                       # Default is to use one thread.
DO_HELP=0                       # Does the help need to be displayed?
ZLEVEL=""                       # use the default
XLEVEL=""

errors=0

while getopts "ht:" opt         # Add this "x:z:" back in when implemented
do
    case "$opt" in
        (\?) ((errors++)) ;;
        (h) DO_HELP=1 ;;
        (t) THREADS=$OPTARG ;;
        (x) NYI -x XLEVEL=$OPTARG ;;
        (z) NYI -z ZLEVEL=$OPTARG ;;
    esac
done
exit 1


((DO_HELP)) && HELPOUT=/dev/stdout || HELPOUT=/dev/stderr

((DO_HELP || errors)) && {
    cat >$HELPOUT <<EOF
usage: $0 [-tn]

Options
-h      Displays this message.
-tn	Sets the number of threads to use.  Default: 1.
EOF
    exit
}

if [[ -n $ZLEVEL ]]; then       # Non default level specified
    ZLEVELFILEPART="ZL$ZLEVEL"
else
    ZLEVELFILEPART="ZL-default"
fi

if [[ -n $XLEVEL ]]; then       # Non default level specified
    XLEVELFILEPART="XL$XLEVEL-"
else
    XLEVELFILEPART="XL-default-"
fi

{
    echo "command line: $@"

    shift $((OPTIND-1))

    TESTFILE=$1

    time {
        echo "==== sha512sum $TESTFILE >$TESTFILE.sha512sum"
        time sha512sum $TESTFILE >$TESTFILE.sha512sum
        
        echo "==== xz --compress --threads=$THREADS <$TESTFILE >$XLEVELFILEPART-T$THREADS-$TESTFILE.xz at $(date -Iseconds)"
        ls -l $TESTFILE
        ls -lh $TESTFILE
        time xz --compress --threads=$THREADS <$TESTFILE >$XLEVELFILEPART-T$THREADS-$TESTFILE.xz
        ls -l $XLEVELFILEPART-T$THREADS-$TESTFILE.xz
        ls -lh $XLEVELFILEPART-T$THREADS-$TESTFILE.xz
        echo "==== xz --decompress --threads=$THREADS <$XLEVELFILEPART-T$THREADS-$TESTFILE.xz >$XLEVELFILEPART-T$THREADS-$TESTFILE.c2 at $(date -Iseconds)"
        time xz --decompress --threads=$THREADS <$XLEVELFILEPART-T$THREADS-$TESTFILE.xz >$XLEVELFILEPART-T$THREADS-$TESTFILE.c2
        echo "sha512sum $XLEVELFILEPART-T$THREADS-$TESTFILE.c2 >$XLEVELFILEPART-T$THREADS-$TESTFILE.c2.sha512sum"
        echo "==== sha512sum $XLEVELFILEPART-T$THREADS-$TESTFILE.c2 >$XLEVELFILEPART-T$THREADS-$TESTFILE.c2.sha512sum"
        time sha512sum $XLEVELFILEPART-T$THREADS-$TESTFILE.c2 >$XLEVELFILEPART-T$THREADS-$TESTFILE.c2.sha512sum
        echo "==== diff $TESTFILE.sha512sum $XLEVELFILEPART-T$THREADS-$TESTFILE.c2.sha512sum"
        diff $TESTFILE.sha512sum $XLEVELFILEPART-T$THREADS-$TESTFILE.c2.sha512sum

        echo "==== zstd --threads=$THREADS  -19 <$TESTFILE >$ZLEVELFILEPART-T$THREADS-$TESTFILE.zstd at $(date -Iseconds)"
        time zstd --threads=$THREADS -19 <$TESTFILE >$ZLEVELFILEPART-T$THREADS-$TESTFILE.zstd
        ls -l $ZLEVELFILEPART-T$THREADS-$TESTFILE.zstd
        ls -lh $ZLEVELFILEPART-T$THREADS-$TESTFILE.zstd
        echo "==== zstd -d --threads=$THREADS <$ZLEVELFILEPART-T$THREADS-$TESTFILE.zstd >$ZLEVELFILEPART-T$THREADS-$TESTFILE.c3 at $(date -Iseconds)"
        time zstd -d <$ZLEVELFILEPART-T$THREADS-$TESTFILE.zstd >$ZLEVELFILEPART-T$THREADS-$TESTFILE.c3
        echo "==== sha512sum $ZLEVELFILEPART-T$THREADS-$TESTFILE.c3 >$ZLEVELFILEPART-T$THREADS-$TESTFILE.c3.sha512sum"
        time sha512sum $ZLEVELFILEPART-T$THREADS-$TESTFILE.c3 >$ZLEVELFILEPART-T$THREADS-$TESTFILE.c3.sha512sum
        echo "==== Diffing $TESTFILE.sha512sum and $ZLEVELFILEPART-T$THREADS-$TESTFILE.C3.sha512sum"
        diff $TESTFILE.sha512sum $ZLEVELFILEPART-T$THREADS-$TESTFILE.c3.sha512sum
        echo "==== Done at $(date -Iseconds)"
    }
} 2>&1 | log compare-xz-zstd
