#! /usr/bin/env bash
# See: https://src.alexschroeder.ch/text-mapper.git

cd /usr/local/sw/src/gaming/text-mapper &&
    podman run --publish=3010:3010 test/text-mapper \
           text-mapper daemon --listen "http://*:3010"
