#! /usr/bin/env bash

trap 'echo "trap hit, exiting..."; exit' SIGINT

while getopts "Chp:" opt
do
    case "$opt" in
        (\?) ((errors++)) ;;
        (C) DO_CREATE='-C' ;;
        (h) DO_HELP=1 ;;
        (p) LOWEST_PRIO="$OPTARG" ;;
    esac
done

((DO_HELP)) && HELPOUT=/dev/stdout || HELPOUT=/dev/stderr
((DO_HELP || errors)) && {
    cat >$HELPOUT <<EOF
usage: $0 [-Chp]

Options
-C      Prompt to create missing repositories.
-h	Displays this message.
-pP     Number P is lowest priority to pull.
EOF
    exit
}

[[ -n "$LOWEST_PRIO" ]] && USEPRIO=-p$LOWEST_PRIO

HOSTS=(
    elric
    ilian
    konrad
    ulrich
)
for host in "${HOSTS[@]}"; do
    # [[ $(hostname) == $host ]] && next
    echo "====> Working on $host"
    ssh -t tkb@$host "bash -l git-outofdate -u $USEPRIO $DO_CREATE"
done

