#! /usr/bin/env bash

trap 'echo "trap hit, exiting..."; exit' SIGINT

while getopts "Chp:s:" opt
do
    case "$opt" in
        (\?) ((errors++)) ;;
        (C) DO_CREATE='-C' ;;
        (h) DO_HELP=1 ;;
        (p) LOWEST_PRIO="$OPTARG" ;;
        (s) SKIP_HOSTS="$OPTARG" ;;
    esac
done

((DO_HELP)) && HELPOUT=/dev/stdout || HELPOUT=/dev/stderr
((DO_HELP || errors)) && {
    cat >$HELPOUT <<EOF
usage: $0 [-Chp -skiphosts]

Options
-C              Prompt to create missing repositories.
-h	        Displays this message.
-s skiphosts	Specifies 
-pP             Number P is lowest priority to pull.
EOF
    exit
}

[[ -n "$LOWEST_PRIO" ]] && USEPRIO=-p$LOWEST_PRIO

HOSTS=(
    elric
    ilian
    konrad
    ulrich
)
for host in "${HOSTS[@]}"; do
    [[ -n "$SKIP_HOSTS" ]] && [[ "$SKIP_HOSTS" == *"$host"* ]] && continue
    # [[ $(hostname) == $host ]] && continue
    echo "====> Working on $host"
    ssh -t tkb@$host "bash -l git-outofdate -u $USEPRIO $DO_CREATE"
done

