#! /usr/bin/env bash

if [[ -t 0 ]]; then
    MAGENTA='\033[1;35m'        # Repo doesn't exist or is not a git repo.
    CYAN='\033[1;36m'           # Repo name (and prefix).
    YELLOW='\033[1;33m'         # Repo may need pushed.
    GREEN='\033[1;32m'          # Repo ok.
    RED='\033[1;31m'            # Repo may need checkin.
    BLUE='\033[1;34m'           # Repo needs to pull.
    BRIGHTBLUE='\u001b[34;1m'   # Repo needs to push.
    BRIGHTRED='\u001b[31;1m'    # 
    BRIGHTWHITE='\u001b[37;1m'  # Status didn't match.
    BRIGHTYELLOW='\u001b[33;1m' # Repo diverged. 
    NC='\033[0m'                # No Color.
fi


mygitrepos --all-columns | while read PRIORITY INCLUDE DIR REPO
do
    if ! [[ -d $DIR ]]; then 
        printf "===> ${MAGENTA}%20s ${CYAN}Repo $DIR$NC\n" "Does not exist!"
        [[ $INCLUDE != y ]] && {
            printf "     ${BRIGHTWHITE}But we are ignoring it!$NC\n"
            continue
        }
        PARENTDIR=$(dirname $DIR)
        REPODIR=$(basename $DIR)
        echo PARENTDIR: $PARENTDIR REPODIR: $REPODIR
        (mkdir -pv $PARENTDIR && cd $PARENTDIR &&
             git clone $REPO $REPODIR)
    elif ! [[ -d $DIR/.git ]]; then 
        printf "===> ${MAGENTA}%20s ${CYAN}Repo $DIR$NC\n" "Not a git repo!"
        continue
    fi
done
