#! /usr/bin/env bash
DO_INTERACTIVE=0
errors=0

while getopts "hi" opt
do
    case "$opt" in
        (\?) ((errors++)) ;;
        (h) DO_HELP=1 ;;
        (i) DO_INTERACTIVE=1 ;;
    esac
done

((DO_HELP)) && HELPOUT=/dev/stdout || HELPOUT=/dev/stderr
((DO_HELP || errors)) && {
    cat >$HELPOUT <<EOF
usage: $0 [-ln]

Options
-c      Clears the screen.
-h	Displays this message.
EOF
    exit
}

shift $((OPTIND-1))
if [[ -t 0 ]]; then
    MAGENTA='\033[1;35m'        # Repo doesn't exist or is not a git repo.
    CYAN='\033[1;36m'           # Repo name (and prefix).
    YELLOW='\033[1;33m'         # Repo may need pushed.
    GREEN='\033[1;32m'          # Repo ok.
    RED='\033[1;31m'            # Repo may need checkin.
    BLUE='\033[1;34m'           # Repo needs to pull.
    BRIGHTBLUE='\u001b[34;1m'   # Repo needs to push.
    BRIGHTRED='\u001b[31;1m'    # 
    BRIGHTWHITE='\u001b[37;1m'  # Status didn't match.
    BRIGHTYELLOW='\u001b[33;1m' # Repo diverged. 
    NC='\033[0m'                # No Color.
fi


mygitrepos --all-columns | while read PRIORITY INCLUDE DIR REPO
do
    if ! [[ -d $DIR ]]; then 
        printf "===> ${MAGENTA}%20s ${CYAN}Repo $DIR$NC\n" "Does not exist!"
        [[ $INCLUDE != y ]] && {
            printf "     ${BRIGHTWHITE}But we are ignoring it!$NC\n"
            continue
        }
        CREATE_REPO=1
        PARENTDIR=$(dirname $DIR)
        REPODIR=$(basename $DIR)
        echo PARENTDIR: $PARENTDIR REPODIR: $REPODIR
        echo DO_INTERACTIVE: $DO_INTERACTIVE
        ((DO_INTERACTIVE)) && echo interactive || echo non-interactive
        ((DO_INTERACTIVE)) && {
            read -p "Create repo? (y/n/q)" ynq </dev/tty
            echo ynq: $ynq
            [[ $ynq == [Qq]* ]] && {
                echo 1>&2 "User requested quit, exiting."
                exit 1
            }
            [[ $ynq == [Yy]* ]] && CREATE_REPO=1
        } || {
            CREATE_REPO=0
        }
        ((CREATE_REPO)) &&
            (mkdir -p $PARENTDIR && cd $PARENTDIR &&
                 git clone $REPO $REPODIR)
    elif ! [[ -d $DIR/.git ]]; then 
        printf "===> ${MAGENTA}%20s ${CYAN}Repo $DIR$NC\n" "Not a git repo!"
        continue
    fi
done
