#! /usr/bin/env bash

git config --global pull.rebase false  # merge

git config --global user.email "tkurtbond@gmail.com"
git config --global user.name "T. Kurt Bond"

git config --global init.defaultBranch main
