#! /usr/bin/env bash

FONTSIZE=${1:-18}
java -DWindows.controlFont=DejaVuSans-plain-${FONTSIZE} -DWindows.menuFont=DejaVuSans-plain-${FONTSIZE} -DPlastic.controlFont=DejaVuSans-plain-${FONTSIZE} -DPlastic.menuFont=DejaVuSans-bold-${FONTSIZE} -jar /usr/local/sw/versions/hero-designer/HD6.jar
