#! /usr/bin/env python3

import sqlite3
# substitute username with your username
conn = sqlite3.connect('/Users/tkb/Library/Messages/chat.db')
# connect to the database
cur = conn.cursor()
# get the names of the tables in the database
cur.execute(" select name from sqlite_master where type = 'table' ")
for name in cur.fetchall():
    print(name)
