#! /usr/bin/env bash

[[ -e scan.pdf ]] && mv -v scan.pdf scan0000.pdf

find . -maxdepth 1 -type f -name \*.pdf | sort |
    while read fn; do
        ((i++))
        mv  -v $fn $(printf "%02d-.pdf\n" $i)
    done
