#!/bin/sh

if [ $# -eq 0 ]
then
    cmd="netscape -remote 'openBrowser()'"
elif [ "$1" = "-file" ]
then
    shift
    file=$1
    case $file in
    /*)				# absolute; do nothing
    ;;
    *)				# Relative; append pwd
        file="$(pwd)/$file"
    ;;
    esac
    cmd="netscape -noraise -remote 'openFile($file,new-window)'"
else
    cmd="netscape -noraise -remote 'openURL($1,new-window)'"
fi
eval $cmd
if [ $? -ne 0 ]
then
    echo oops
    netscape &
    sleep 5s
    eval $cmd
fi
