#! /usr/bin/env bash

# On macOS, the -n (new instance) option is very helpful when you want
# to look at two different parts of the document at the same time.
# xdg-open doesn't have any useful options.

USE_OKULAR=
USE_EVINCE=
let errors=0
while getopts "eow:" opt
do
    case "$opt" in
        (\?) let errors++ ;;
        (e) USE_EVINCE=true ;;
        (o) USE_OKULAR=true ;;
        (w) WAIT_TIME="$OPTARG" ;;
    esac
done
if [ "$errors" -gt 0 ]
then
    cat <<EOF
usage: $0 [-o] file ...
where
-o	Open with Okular
-e      Open with Evince
-w TIME Use sleep to Wait TIME before opening files after the first.
EOF
    exit 2
fi
let shift_by=OPTIND-1
shift $shift_by

((ITEMS=0))
case "$(uname -s)" in
    (Linux)
        for i in "$@"
        do
            if ((ITEMS)); then sleep $WAIT_TIME; fi
            if [[ -n "$USE_OKULAR" ]]; then
                spwn okular "$i"
            elif [[ -n "$USE_EVINCE" ]]; then
                spwn evince "$i"
            else
                spwn xdg-open "$i"
            fi
            ((ITEMS++))
        done
        ;;
    (Darwin)
        open "$@"
        ;;
esac
