#! /usr/bin/env python3

import re, sys

name_re = re.compile (r":name:`([-\w\s.]+)`", re.MULTILINE)

if len (sys.argv) <= 1:
    sys.stderr.write ("""usage: find-names file ...
    Finds names specified with reST role name.""")
    sys.exit (2)

for filename in sys.argv[1:]:
    file = open (filename, "r")
    text = file.read ()
    file.close ()
    text = text.replace ("\n", " ")
    names = re.findall (name_re, text)
    for name in names:
        print (name)
