#! /usr/bin/env bash

while true
do
    echo ===== $(date "+%F %T") =========================
    ping -e -c10 8.8.8.8
    read -t 10 -p "Continue? (y/n) " reply
    if (($?>128)); then
	echo "timed out, continuing..."
    elif [[ "$reply" =~ [Nn] ]]; then
	echo "Exiting..."
	exit
    else
	echo "Continuing..."
    fi
done
