#! /usr/bin/env bash

INDENT=8
WIDTH=78
((errors=0))
while getopts "i:w:" opt
do
    case $opt in
        (\?) ((errors++)) ;;
        (i) INDENT="$OPTARG" ;;
        (w) WIDTH="$OPTARG" ;;
    esac
done

((errors > 0)) &&
    { echo 1>&2 "Error: usage: $0 [-iINDENT] [-wWIDTH]"
      exit 127
    }

INDENT_STRING="$(printf '%*s' $INDENT ' ' | unexpand)"

tr ' \t\\' '\n' | sed -r '/^\s*$/d' | sort | tr '\n' ' ' |
    fmt -w $((WIDTH - INDENT)) |
    sed "s/^/$INDENT_STRING/" | sed '$!s/$/ \\/'
