#! /usr/bin/bash
while true
do
    ((i++))
    echo "Run #$i of dnf update at $(date -Iseconds)"
    dnf -y upgrade && break     # Exit loop on success

    # This allows the user to exit if necessary.
    read -t 30 -p "Continue? (y/n) " reply
    if (($?>128)); then
	echo "timed out, continuing..."
    elif [[ "$reply" =~ [Nn] ]]; then
	echo "Exiting..."
	exit
    else
	echo "Continuing..."
    fi
done
