#! /usr/bin/env bash

function iterate {
    for profile in "$@"
    do
        if [[ -z "$DISPLAY" && -z "$WAYLAND_DISPLAY" ]]; then
            unison -ui text $profile
        else
            unison $profile &
        fi
    done
}

HOSTNAME=$(hostname)
echo HOSTNAME: $HOSTNAME

if [[ $HOSTNAME = helblindi ]]; then
    export MEDIA=/media/tkb
else
    export MEDIA=/run/media/tkb
fi

ALWAYS=(
    $HOSTNAME-tkb-to-ulrich
    $HOSTNAME-tkb-to-ulrich-d1tkb
    $HOSTNAME-tkb-to-ilian
    $HOSTNAME-tkb-to-konrad
    $HOSTNAME-tkb-to-elric
    $HOSTNAME-tkb-to-elric-fensalir
    # $HOSTNAME-tkb-to-smiorgan
    # $HOSTNAME-tkb-to-cornelius
)

IFKORMT=(
    $HOSTNAME-kormt-to-ulrich-d1tkb
    $HOSTNAME-kormt-to-ulrich-jotunheim
    $HOSTNAME-kormt-to-elric-fensalir
)


iterate "${ALWAYS[@]}"

[[ -d $MEDIA/Kormt ]] && iterate "${IFKORMT[@]}"
