#! /usr/bin/env python

import mailbox
import sys
import os

def process_file (filename):
    num_files = 0
    inf = open (filename, "r")
    mb = mailbox.UnixMailbox (inf)
    while 1:
	message = mb.next ()
	if not message: break
	content_type = message.getheader ("Content-Type")
	if content_type: print "content_type: ", content_type
	outfilename = "msg.%d" % num_files
	num_files = num_files + 1
	outf = open (outfilename, "w")
	print outfilename
	for line in message.headers:
	    outf.write (line)
	outf.write ("\n")
	while 1:
	    line = message.fp.readline ()
	    if not line: break
	    outf.write (line)
	outf.close ()
	if content_type: os.system ("METAMAIL_TMPDIR=. metamail -w -x < %s" % outfilename)
	else: os.system ("uudecode < %s" % outfilename)
    inf.close ()

def main ():
    for filename in sys.argv[1:]:
	process_file (filename)

if __name__ == "__main__":
    main ()
