#!/bin/sh
#
# From: https://unix.stackexchange.com/a/195911
# 
# Print the specified (or current) time from base time in other time zones
# and the converse
#
# usage: usatime HH:MM{pm|am}

# Base time zone from/to which to convert
#TZBASE=Europe/Athens
TZBASE=America/New_York

# Time zones to display
# See /usr/share/zoneinfo/ for more names
TZONES='America/New_York America/Chicago America/Denver America/Los_Angeles'

# Display format
#FORMAT='%H:%M (%p) %Z %a %m %b %Y'
#FORMAT='%I:%M %p %Z (%H:%M) %a %m %b %Y'
FORMAT='%I:%M %p %Z (%H:%M)'

if [ "$1" ] ; then
  time="$1"
else
  time=`date +%T`
fi

# Show the time from the specified input time zone in the specified output
# time zone
showtime()
{
  TZIN=$1
  TZOUT=$2

  printf "%20s -> %20s: " $TZIN $TZOUT
  TZ=$TZOUT date --date='TZ="'$TZIN'"'" $time" +"$time is $FORMAT"
}

for tz in $TZONES ; do
  showtime $TZBASE $tz
done

echo

