#! /usr/bin/env bash

HOSTNAME=$(hostname)
echo HOSTNAME: $HOSTNAME

unison $HOSTNAME-tkb-to-oone &
unison $HOSTNAME-tkb-to-oone-muspelheim &


if [[ -d /var/run/media/tkb/Kormt ]]; then
    unison $HOSTNAME-kormt-to-oone-muspelheim &
    unison $HOSTNAME-tkb-kormt &
fi

if [[ -d /var/run/media/tkb/Sindri ]]; then
    unison $HOSTNAME-tkb-sindri &
fi
