#! /usr/bin/env bash

function iterate {
    for profile in "$@"
    do
        if [[ -z "$DISPLAY" && -z "$WAYLAND_DISPLAY" ]]; then
            unison $profile
        else
            unison $profile &
        fi
    done
}

HOSTNAME=$(hostname)
echo HOSTNAME: $HOSTNAME

if [[ $HOSTNAME = helblindi ]]; then
    export MEDIA=/media/tkb
else
    export MEDIA=/run/media/tkb
fi

ALWAYS=($HOSTNAME-tkb-to-oone $HOSTNAME-tkb-to-oone-muspelheim)
IFKORMT=($HOSTNAME-kormt-to-oone-muspelheim $HOSTNAME-tkb-kormt)
IFSINDRI=($HOSTNAME-tkb-sindri)

iterate ${ALWAYS[@]}
[[ -d $MEDIA/Kormt ]] && iterate ${IFKORMT[@]}
[[ -d $MEDIA/Sindri ]] && iterate ${IFSINDRI[@]}
