#!/usr/bin/env bash

COLUMNS=$(tput cols)
LINES=$(tput lines)

DEVICE=/DEVICE=VT100
[[ $1 == "-i" ]] && DEVICE=/inquire

# was /INQ instead of /DEVICE=VT100.  Changed to better deal with EDIT/TPU.

echo "
set term${DEVICE}/insert/page=$LINES/width=$COLUMNS
"
