#! /usr/bin/env bash

function die () { 
    RET=$1; shift 
    echo 1>&2 "$*" 
    echo "=========> Error, exiting at $(date -Iseconds)"
    exit $RET 
}


HOSTNAME="$(hostname)"
DESTDIR=/run/media/tkb/Utgard/From-NAS

find /media/tkb/vaxtapes -name \*.vtape | sort | while read FN
do
    echo echo $FN
    DIRNAME="$(dirname $FN)"
    BASNAME="$(basename $FN)"
    DSTNAME="$DESTDIR/$BASNAME"
    CMPNAME="$BASNAME.xz"
    [[ -e $DESTDIR/$BN.xz ]] && {
        echo "DESTDIR/$BN.xz already exists, skipping $FN"
        continue
    }
    time cp -v $FN $DESTDIR/ || die 1 "Error copying $FN to $DESTDIR, exiting."
    (cd $DESTDIR
     time sha512sum --binary $BASNAME 
     time xz --compress $BASEFN)
done
