#! /usr/bin/env bash

function die () { 
    RET=$1; shift 
    echo 1>&2 "$*" 
    echo "=========> $(date -Iseconds) - Error, exiting."
    exit $RET 
}


HOSTNAME="$(hostname)"
DESTDIR="/run/media/tkb/Utgard/From-NAS"

{
    echo "==========> $(date -Iseconds) - Starting copy, sum, and compress."
    NUMFILES="$(find /media/tkb/vaxtapes -name \*.vtape | wc -l)"

    find /media/tkb/vaxtapes -name \*.vtape | sort | while read FN
    do
        ((FILENUM++))
        echo "==========> $(date -Iseconds) Working on file #$FILENUM of $NUMFILES $FN"
        DIRNAME="$(dirname $FN)"
        BASENAME="$(basename $FN)"
        DESTNAME="$DESTDIR/$BASNAME"
        COMPNAME="$BASENAME.xz"
        
        [[ -e $DESTDIR/$COMPNAME ]] && {
            echo "DESTDIR/$COMPNAME already exists, skipping $FN"
            continue
        }
        echo "==========> $(date -Iseconds) - Copying $FN to $DESTDIR"
        time cp -v $FN $DESTDIR/ || die 1 "Error copying $FN to $DESTDIR."
        (
            cd $DESTDIR
            echo "==========> $(date -Iseconds) - sha512sum $BASENAME"
            time sha512sum --binary $BASENAME >$BASENAME.sha512sum.$HOSTNAME ||
                die 1 "Error sha512summing $BASENAME."
            echo "==========> $(date -Iseconds) - xz --compress $BASENAME"
            time xz --compress $BASENAME ||
                die "Error xz --compressing $BASENAME."
        )
        scream
    done
    echo "==========>  at $(date -Iseconds) - Finished copy, sum, and compress"
} 2>&1 | log ~/tmp/vtape-cp-sum-and-xz
