#! /usr/bin/env bash

LIMIT=0
export num_files=0
errors=0

while getopts "hl:n" opt
do
    case "$opt" in
        (\?) ((errors++)) ;;
        (h) DO_HELP=1 ;;
        (l) LIMIT="$OPTARG" ;;
        (n) DRY_RUN=1 ;;
    esac
done

((DO_HELP)) && ERROUT=/dev/stdout || ERROUT=/dev/stderr

((DO_HELP || errors)) && {
    cat >$ERROUT <<EOF
usage: $0 [-ln]

Options
-h      Displays this message.
-ln	Sets the maximum number of files to process.
EOF
    exit
}

shift $((OPTIND-1))

time (find "$@" -type f -name \*.vtape | sort | while read FILENAME
      do
          ((num_files++))
          ((LIMIT && num_files > LIMIT)) && {
              echo 2>&1 Exiting after processing $LIMIT files
              break
          }
          printf "%.0s" {1..80}
          print
          echo $num_files: $FILENAME at $(iso8601)
          ((DRY_RUN)) || {
              echo $FILENAME sha512sum
              time sha512sum $FILENAME >$FILENAME.sha512sum
              echo $FILENAME xz --compress
              time /bin/xz --compress $FILENAME
          }
      done)
echo Finished at $(iso8601)
