#! /usr/bin/env bash
while getopts "chn:" opt
do
    case "$opt" in
        (\?) ((errors++)) ;;
        (c) CONTINUOUS=1 ;;
        (h) DO_HELP=1 ;;
        (n) LIMIT=$OPTARG ;;
    esac
done
((DO_HELP)) && HELPOUT=/dev/stdout || HELPOUT=/dev/stderr

((DO_HELP || errors)) && {
    cat >$HELPOUT <<EOF
usage: $0 [-tn]

Options
-c      Ding continously.
-h      Displays this message.
-nN     Ding N times.
EOF
    exit
}

let n=0
while ((CONTINUOUS || n < LIMIT))
do
    ((n > 0)) && sleep 1
    ogg123 /usr/share/sounds/freedesktop/stereo/bell.oga </dev/null >/dev/null 2>&1
    ((n++))
done
