#! /usr/bin/env python

import sys, yaml, argparse

parser = argparse.ArgumentParser ()
parser.add_argument ('input_file')
parser.add_argument ('--flow', help='output in flow style', action="store_true")
args = parser.parse_args ()

with open(args.input_file) as f:
   yaml.safe_dump (yaml.safe_load(f), stream=sys.stdout,
                   default_flow_style=args.flow)

